<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="TUnit" Version="1.63.0" />
    <PackageVersion Include="TUnit.Core" Version="1.63.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="5.6.0" />
  </ItemGroup>
  <ItemGroup>
    <GlobalPackageReference Include="Nerdbank.GitVersioning" Version="3.10.91" />
  </ItemGroup>
</Project>
