namespace TUnit.PairwiseDataSource.FailureScenarios;

public enum FailureScenarioColor
{
    Red,
    Green,
}

public class BooleanExcludingFailureScenarios
{
    [Test]
    [PairwiseDataSource]
    public async Task ExcludingBooleanValues_ShouldFail(
        [Matrix(Excluding = new object[] { true })] bool value)
    {
        await Task.CompletedTask;
    }
}

public class NullableEnumNullExcludingFailureScenarios
{
    [Test]
    [PairwiseDataSource]
    public async Task ExcludingNullFromNullableEnum_ShouldFail(
        [Matrix(Excluding = new object?[] { null })] FailureScenarioColor? value)
    {
        await Task.CompletedTask;
    }
}

public class MissingMatrixAttributeFailureScenarios
{
    [Test]
    [PairwiseDataSource]
    public async Task NonAutoGeneratedParameterWithoutMatrix_ShouldFail(int value)
    {
        await Task.CompletedTask;
    }
}
