using TUnit.Core;
using TUnit.Core.Enums;
using TUnit.Core.Extensions;

namespace TUnit.PairwiseDataSource;

/// <summary>
/// Generates test cases using a pairwise (all-pairs) strategy, ensuring that
/// every pair of parameter values is covered by at least one test case.
/// </summary>
/// <remarks>
/// <para>
/// This produces significantly fewer test cases than the full Cartesian product
/// generated by <see cref="MatrixDataSourceAttribute"/>, while still covering
/// all pairwise combinations. Research shows that most software defects are
/// triggered by interactions between at most two parameters, making pairwise
/// testing an effective strategy for reducing test count without sacrificing
/// meaningful coverage.
/// </para>
/// <para>
/// For boolean parameters, all values (<c>true</c>, <c>false</c>) are generated automatically.
/// For enum parameters, all defined enum values are generated automatically.
/// For other types, use <c>[Matrix(...)]</c> on individual parameters to specify the values.
/// </para>
/// <para>
/// Use <see cref="MatrixExclusionAttribute"/> on the test method to exclude specific combinations.
/// </para>
/// </remarks>
/// <example>
/// <code>
/// [Test, PairwiseDataSource]
/// public void TestPairwise(
///     [Matrix("a", "b", "c")] string x,
///     [Matrix("+", "-")] string y,
///     [Matrix("1", "2")] string z)
/// {
///     // Generates ~6 test cases covering all pairs, instead of 12 (3x2x2) combinations
/// }
///
/// [Test, PairwiseDataSource]
/// public void TestWithEnum(bool enabled, MyEnum mode)
/// {
///     // Automatically generates pairwise combinations of bool x enum values
/// }
/// </code>
/// </example>
[AttributeUsage(AttributeTargets.Class | AttributeTargets.Method)]
public sealed class PairwiseDataSourceAttribute : UntypedDataSourceGeneratorAttribute, IAccessesInstanceData
{
    /// <inheritdoc />
    protected override IEnumerable<Func<object?[]?>> GenerateDataSources(DataGeneratorMetadata dataGeneratorMetadata)
    {
        var parameterInformation = dataGeneratorMetadata
            .MembersToGenerate
            .OfType<ParameterMetadata>()
            .ToArray();

        if (parameterInformation.Length != dataGeneratorMetadata.MembersToGenerate.Length
            || parameterInformation.Length is 0)
        {
            throw new Exception("[PairwiseDataSource] only supports parameterised tests");
        }

        if (dataGeneratorMetadata.TestInformation == null)
        {
            throw new InvalidOperationException("PairwiseDataSource requires test information but none is available. This may occur during static property initialization.");
        }

        var testInformation = dataGeneratorMetadata.TestInformation;
        var classType = testInformation.Class.Type;

        var exclusions = GetExclusions(dataGeneratorMetadata.Type == DataGeneratorType.TestParameters
            ? dataGeneratorMetadata.TestInformation.GetCustomAttributes()
            : classType.GetCustomAttributesSafe());

        var allValues = parameterInformation
            .Select(p => GetAllArguments(dataGeneratorMetadata, p))
            .ToArray();

        // For 0 or 1 parameters, pairwise is the same as full enumeration
        if (allValues.Length <= 1)
        {
            foreach (var row in GetCartesianProduct(allValues))
            {
                var rowArray = row.ToArray();
                if (!exclusions.Any(e => IsExcluded(e, rowArray)))
                {
                    yield return () => rowArray;
                }
            }

            yield break;
        }

        int[] dimensions = [.. allValues.Select(v => v.Count)];
        int[][] testCaseIndices = PairwiseStrategy.GetTestCases(dimensions);

        foreach (int[] testCase in testCaseIndices)
        {
            var rowArray = new object?[testCase.Length];
            for (int i = 0; i < testCase.Length; i++)
            {
                rowArray[i] = allValues[i][testCase[i]];
            }

            if (!exclusions.Any(e => IsExcluded(e, rowArray)))
            {
                yield return () => rowArray;
            }
        }
    }

    private static bool IsExcluded(object?[] exclusion, object?[] rowArray)
    {
        if (exclusion.Length != rowArray.Length)
        {
            return false;
        }

        for (int i = 0; i < exclusion.Length; i++)
        {
            var exclusionValue = exclusion[i];
            var rowValue = rowArray[i];

            if (exclusionValue != null && exclusionValue.GetType().IsEnum)
            {
                exclusionValue = Convert.ChangeType(exclusionValue, Enum.GetUnderlyingType(exclusionValue.GetType()));
            }

            if (rowValue != null && rowValue.GetType().IsEnum)
            {
                rowValue = Convert.ChangeType(rowValue, Enum.GetUnderlyingType(rowValue.GetType()));
            }

            if (!Equals(exclusionValue, rowValue))
            {
                return false;
            }
        }

        return true;
    }

    private static object?[][] GetExclusions(IEnumerable<Attribute> attributes)
    {
        return attributes
            .Where(x => x is MatrixExclusionAttribute)
            .Cast<MatrixExclusionAttribute>()
            .Select(x => x.Objects)
            .ToArray();
    }

    private static IReadOnlyList<object?> GetAllArguments(
        DataGeneratorMetadata dataGeneratorMetadata,
        ParameterMetadata sourceGeneratedParameterInformation)
    {
        MatrixAttribute? matrixAttribute;

        if (sourceGeneratedParameterInformation.CachedDataSourceAttributes != null)
        {
            matrixAttribute = sourceGeneratedParameterInformation.CachedDataSourceAttributes
                .OfType<MatrixAttribute>()
                .FirstOrDefault();
        }
        else
        {
            if (sourceGeneratedParameterInformation.ReflectionInfo == null)
            {
                throw new InvalidOperationException($"Parameter reflection information is not available for parameter '{sourceGeneratedParameterInformation.Name}'. This typically occurs when using instance method data sources which are not supported at compile time.");
            }

            matrixAttribute = sourceGeneratedParameterInformation.ReflectionInfo.GetCustomAttributesSafe()
                .OfType<MatrixAttribute>()
                .FirstOrDefault();
        }

        if (matrixAttribute is IAccessesInstanceData && dataGeneratorMetadata.TestClassInstance == null)
        {
            var className = dataGeneratorMetadata.TestInformation?.Class.Type.Name ?? "Unknown";
            if (dataGeneratorMetadata.TestInformation?.Class.Type.IsGenericTypeDefinition ?? false)
            {
                throw new InvalidOperationException(
                    $"Cannot use MatrixInstanceMethod attribute in generic class '{className}' when the generic type parameters " +
                    $"must be inferred from the matrix values. This creates a circular dependency: " +
                    $"the instance is needed to get the matrix values, but the generic types (which come from the matrix values) " +
                    $"are needed to create the instance. Consider using static methods for matrix data sources in generic classes, " +
                    $"or provide the generic type arguments explicitly using [Arguments] or other data source attributes.");
            }

            throw new InvalidOperationException(
                $"Instance is required for MatrixInstanceMethod but no instance is available. " +
                $"This typically happens when the test class requires data that hasn't been expanded yet.");
        }

        var objects = matrixAttribute?.GetObjects(dataGeneratorMetadata);

        if (matrixAttribute is not null && objects is { Length: > 0 })
        {
            return matrixAttribute.Excluding is not null
                       ? objects.Except(matrixAttribute.Excluding).ToArray()
                       : objects;
        }

        var type = sourceGeneratedParameterInformation.Type;

        Type? underlyingType = null;
        var isNullable = sourceGeneratedParameterInformation.IsNullable;

        if (isNullable)
        {
            underlyingType = Nullable.GetUnderlyingType(type);

            if (underlyingType == null && type.IsGenericType && type.GetGenericArguments().Length == 1)
            {
                underlyingType = type.GetGenericArguments()[0];
            }
        }

        var resolvedType = underlyingType ?? type;

        if (resolvedType == typeof(bool))
        {
            if (matrixAttribute?.Excluding is not null)
            {
                throw new InvalidOperationException("Do not exclude values from a boolean.");
            }

            return isNullable ? [true, false, null] : [true, false];
        }

        if (resolvedType.IsEnum)
        {
            var enumValues = GetEnumValuesAsUnderlyingType(resolvedType);

            if (isNullable)
            {
                enumValues = enumValues.Append(null);
                if (matrixAttribute?.Excluding?.Any(x => x is null) ?? false)
                {
                    throw new InvalidOperationException("Do not exclude null from a nullable enum - instead use the enum directly");
                }
            }

            return enumValues
                .Except(matrixAttribute?.Excluding?.Select(e => Convert.ChangeType(e, Enum.GetUnderlyingType(resolvedType))) ?? [])
                .ToArray();
        }

        throw new ArgumentNullException($"No MatrixAttribute found for parameter '{sourceGeneratedParameterInformation.Name}' and the parameter type '{resolvedType.Name}' cannot be auto-generated. Only bool and enum types support auto-generation.");
    }

    /// <summary>
    /// Returns the defined enum values converted to the enum's underlying integral type.
    /// </summary>
    /// <remarks>
    /// Uses <see cref="Enum.GetValuesAsUnderlyingType(Type)"/> where available and falls back
    /// to converting the values from <see cref="Enum.GetValues(Type)"/> on .NET Standard 2.0.
    /// </remarks>
    private static IEnumerable<object?> GetEnumValuesAsUnderlyingType(Type resolvedType)
    {
#if NET7_0_OR_GREATER
        return Enum.GetValuesAsUnderlyingType(resolvedType).Cast<object?>();
#else
        // see also https://github.com/SimonCropp/Polyfill/blob/18243e7e051c347acf023978bd18abd181ea6695/src/Polyfill/EnumPolyfill.cs#L51
        var underlyingType = Enum.GetUnderlyingType(resolvedType);
        return Enum.GetValues(resolvedType)
            .Cast<object>()
            .Select(value => Convert.ChangeType(value, underlyingType));
#endif
    }

    private static readonly IEnumerable<IEnumerable<object?>> Seed = [[]];

    private static IEnumerable<IEnumerable<object?>> GetCartesianProduct(IEnumerable<IReadOnlyList<object?>> elements)
    {
        return elements.Aggregate(Seed, (accumulator, enumerable)
            => accumulator.SelectMany(x => enumerable.Select(x.Append)));
    }
}
