namespace TUnit.PairwiseDataSource.Tests;

public class PairwiseDataSourceAttributeFailureTests
{
    [Test]
    public async Task ExcludingBooleanValues_FailsWithHelpfulMessage()
    {
        var result = await TrxTestProjectRunner.RunFailureScenarioProject("/*/*/BooleanExcludingFailureScenarios/*");

        await Assert.That(result.ExitCode).IsNotEqualTo(0);
        await Assert.That(result.FailedTests).HasSingleItem();
        await Assert.That(result.FailedTests[0].Message).Contains("Do not exclude values from a boolean.");
    }

    [Test]
    public async Task ExcludingNullFromNullableEnum_FailsWithHelpfulMessage()
    {
        var result = await TrxTestProjectRunner.RunFailureScenarioProject("/*/*/NullableEnumNullExcludingFailureScenarios/*");

        await Assert.That(result.ExitCode).IsNotEqualTo(0);
        await Assert.That(result.FailedTests).HasSingleItem();
        await Assert.That(result.FailedTests[0].Message).Contains("Do not exclude null from a nullable enum");
    }

    [Test]
    public async Task MissingMatrixAttributeOnNonAutoGeneratedParameter_FailsWithHelpfulMessage()
    {
        var result = await TrxTestProjectRunner.RunFailureScenarioProject("/*/*/MissingMatrixAttributeFailureScenarios/*");

        await Assert.That(result.ExitCode).IsNotEqualTo(0);
        await Assert.That(result.FailedTests).HasSingleItem();
        await Assert.That(result.FailedTests[0].Message).Contains("No MatrixAttribute found for parameter 'value'");
        await Assert.That(result.FailedTests[0].Message).Contains("cannot be auto-generated");
    }
}
