namespace TUnit.PairwiseDataSource.Tests;

public class PairwiseDataSourceAttributeFailureTests
{
    [Test]
    public async Task ExcludingBooleanValues_FailsWithHelpfulMessage()
    {
        var method = typeof(PairwiseDataSourceAttributeFailureScenarios)
            .GetMethod(nameof(PairwiseDataSourceAttributeFailureScenarios.ExcludingBooleanValues_ShouldFail))!;
        var exception = await PairwiseDataSourceInProcessRunner.GetGenerationExceptionAsync(method);

        await Assert.That(exception.Message).Contains("Do not exclude values from a boolean.");
    }

    [Test]
    public async Task ExcludingNullFromNullableEnum_FailsWithHelpfulMessage()
    {
        var method = typeof(PairwiseDataSourceAttributeFailureScenarios)
            .GetMethod(nameof(PairwiseDataSourceAttributeFailureScenarios.ExcludingNullFromNullableEnum_ShouldFail))!;
        var exception = await PairwiseDataSourceInProcessRunner.GetGenerationExceptionAsync(method);

        await Assert.That(exception.Message).Contains("Do not exclude null from a nullable enum");
    }

    [Test]
    public async Task MissingMatrixAttributeOnNonAutoGeneratedParameter_FailsWithHelpfulMessage()
    {
        var method = typeof(PairwiseDataSourceAttributeFailureScenarios)
            .GetMethod(nameof(PairwiseDataSourceAttributeFailureScenarios.NonAutoGeneratedParameterWithoutMatrix_ShouldFail))!;
        var exception = await PairwiseDataSourceInProcessRunner.GetGenerationExceptionAsync(method);

        await Assert.That(exception.Message).Contains("No MatrixAttribute found for parameter 'value'");
        await Assert.That(exception.Message).Contains("cannot be auto-generated");
    }
}

public static class PairwiseDataSourceAttributeFailureScenarios
{
    public enum FailureScenarioColor
    {
        Red,
        Green,
    }

    [PairwiseDataSource]
    public static Task ExcludingBooleanValues_ShouldFail([Matrix(Excluding = [true])] bool value)
    {
        return Task.CompletedTask;
    }

    [PairwiseDataSource]
    public static Task ExcludingNullFromNullableEnum_ShouldFail(
        [Matrix(Excluding = new object?[] { null })] FailureScenarioColor? value)
    {
        return Task.CompletedTask;
    }

    [PairwiseDataSource]
    public static Task NonAutoGeneratedParameterWithoutMatrix_ShouldFail(int value)
    {
        return Task.CompletedTask;
    }
}
